import { defineConfig } from 'vitepress'

export default defineConfig({
  title: "picoflow.io",
  description: "Tutorial: Medical Appointment Bot using NestJS and PicoFlow.",
  base: '/medical_appt_tutorial/',
  markdown: {
    lineNumbers: true
  },
  head: [
    ['link', { rel: 'icon', href: '/logo.jpg' }],
    ['link', { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap' }],
    ['style', {}, `
      .VPNavBarTitle .title {
        font-family: 'Kaushan Script', cursive !important;
        font-size: 1.8rem !important;
      }
      .VPNavBarTitle .logo {
        height: 48px !important;
        width: auto !important;
        margin-right: 10px !important;
      }
    `]
  ],
  themeConfig: {
    logo: '/logo.jpg',
    logoLink: 'https://www.picoflow.io',
    siteTitle: 'picoflow.io',
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Tutorial', link: '/tutorial/introduction' }
    ],
    sidebar: [
      {
        text: 'Tutorial',
        items: [
          { text: '1. Generated by OpenClaw', link: '/tutorial/introduction' },
          { text: '2. Architecture Overview', link: '/tutorial/architecture' },
          { text: '3. SymptomsStep', link: '/tutorial/symptoms-step' },
          { text: '4. BookingStep', link: '/tutorial/booking-step' },
          { text: '5. React Chat UI', link: '/tutorial/chat-ui' }
        ]
      }
    ]
  }
})